# Generated by Django 5.2.4 on 2025-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_text',
            field=models.TextField(blank=True),
        ),
    ]
