# Generated by Django 4.2.23 on 2025-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcategory_jobposting_job_category'),
        ('users', '0005_auto_20250714_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_job_categories',
            field=models.ManyToManyField(blank=True, help_text='Job categories the user is interested in', related_name='interested_users', to='jobs.jobcategory'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Legacy field - use Resume model instead', null=True, upload_to='resumes/'),
        ),
    ]
