# Generated by Django 4.2.23 on 2025-07-26 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, help_text='OAuth scopes granted')),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('google_user_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=20)),
                ('auto_apply_enabled', models.BooleanField(default=False)),
                ('auto_apply_filters', models.JSONField(blank=True, default=dict, help_text='Job search filters for auto-apply')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if any')),
                ('error_count', models.IntegerField(default=0, help_text='Number of consecutive errors')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Integration',
                'verbose_name_plural': 'Google Integrations',
                'db_table': 'google_integration',
            },
        ),
        migrations.CreateModel(
            name='GoogleAPIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('emails_sent', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('max_emails_per_day', models.IntegerField(default=100)),
                ('max_api_calls_per_day', models.IntegerField(default=1000)),
            ],
            options={
                'verbose_name': 'Google API Quota',
                'verbose_name_plural': 'Google API Quotas',
                'db_table': 'google_api_quota',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AutoApplySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('max_applications', models.IntegerField(default=5, help_text='Maximum applications to send in this session')),
                ('search_filters', models.JSONField(default=dict, help_text='Job search criteria used')),
                ('jobs_found', models.IntegerField(default=0)),
                ('applications_sent', models.IntegerField(default=0)),
                ('applications_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('results_summary', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto Apply Session',
                'verbose_name_plural': 'Auto Apply Sessions',
                'db_table': 'auto_apply_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('email_body', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment info')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_count', models.IntegerField(default=0)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the email')),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_emails', to='applications.jobapplication')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_emails', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Sent Record',
                'verbose_name_plural': 'Email Sent Records',
                'db_table': 'email_sent_record',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('response_type', models.CharField(choices=[('reply', 'Reply'), ('forward', 'Forward'), ('auto_reply', 'Auto Reply'), ('other', 'Other')], default='reply', max_length=20)),
                ('is_automated', models.BooleanField(default=False, help_text='Whether this appears to be an automated response')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether we have processed this response')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Extracted information from the email')),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='google_integration.emailsentrecord')),
            ],
            options={
                'verbose_name': 'Email Response',
                'verbose_name_plural': 'Email Responses',
                'db_table': 'email_response',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='googleintegration',
            index=models.Index(fields=['status'], name='google_integration_status_idx'),
        ),
        migrations.AddIndex(
            model_name='googleintegration',
            index=models.Index(fields=['google_email'], name='google_integration_email_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsentrecord',
            index=models.Index(fields=['gmail_message_id'], name='email_sent_gmail_id_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsentrecord',
            index=models.Index(fields=['status', 'sent_at'], name='email_sent_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresponse',
            index=models.Index(fields=['gmail_message_id'], name='email_response_gmail_id_idx'),
        ),
        migrations.AddIndex(
            model_name='emailresponse',
            index=models.Index(fields=['is_processed'], name='email_response_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapplysession',
            index=models.Index(fields=['status'], name='auto_apply_status_idx'),
        ),
        migrations.AddIndex(
            model_name='autoapplysession',
            index=models.Index(fields=['started_at'], name='auto_apply_started_idx'),
        ),
    ]
