# Generated by Django 4.2.23 on 2025-07-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_integration', '0001_initial'),
    ]

    operations = [
    ]
