# Generated by Django 4.2.23 on 2025-07-26 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_job_posting_job_cat_e80656_idx'),
        ('applications', '0002_jobapplication_external_url_and_more'),
        ('google_integration', '0002_auto_20250726_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoapplysession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='emailresponse',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterModelOptions(
            name='emailsentrecord',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='googleapiquota',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='googleintegration',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='autoapplysession',
            name='auto_apply_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='autoapplysession',
            name='auto_apply_started_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailresponse',
            name='email_response_gmail_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailresponse',
            name='email_response_processed_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailsentrecord',
            name='email_sent_gmail_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailsentrecord',
            name='email_sent_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='googleintegration',
            name='google_integration_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='googleintegration',
            name='google_integration_email_idx',
        ),
        migrations.RemoveField(
            model_name='autoapplysession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailsentrecord',
            name='job_application',
        ),
        migrations.RemoveField(
            model_name='emailsentrecord',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='emailsentrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='autoapplysession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoapplysession',
            name='google_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_sessions', to='google_integration.googleintegration'),
        ),
        migrations.AddField(
            model_name='autoapplysession',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailresponse',
            name='requires_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='google_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='google_integration.googleintegration'),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailsentrecord',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='googleapiquota',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleapiquota',
            name='google_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='google_integration.googleintegration'),
        ),
        migrations.AddField(
            model_name='googleapiquota',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleintegration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleintegration',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleintegration',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoapplysession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autoapplysession',
            name='max_applications',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='autoapplysession',
            name='results_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='autoapplysession',
            name='search_filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='autoapplysession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='autoapplysession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='extracted_data',
            field=models.JSONField(default=dict, help_text='AI-extracted information from response'),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='gmail_message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='is_automated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailresponse',
            name='response_type',
            field=models.CharField(choices=[('reply', 'Direct Reply'), ('auto_reply', 'Auto Reply'), ('interview_invitation', 'Interview Invitation'), ('rejection', 'Rejection'), ('request_info', 'Request for Information'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailsentrecord',
            name='attachments',
            field=models.JSONField(default=list, help_text='List of attachment filenames'),
        ),
        migrations.AlterField(
            model_name='emailsentrecord',
            name='gmail_message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='emailsentrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailsentrecord',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='emailsentrecord',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailsentrecord',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('replied', 'Replied')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='googleapiquota',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='googleapiquota',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='googleapiquota',
            name='max_emails_per_day',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='access_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='auto_apply_filters',
            field=models.JSONField(default=dict, help_text='Job search filters for auto-apply'),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='google_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='scope',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('expired', 'Token Expired'), ('revoked', 'Access Revoked'), ('error', 'Error')], default='disconnected', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='googleapiquota',
            unique_together={('google_integration', 'date')},
        ),
        migrations.AlterModelTable(
            name='autoapplysession',
            table='auto_apply_sessions',
        ),
        migrations.AlterModelTable(
            name='emailresponse',
            table='email_responses',
        ),
        migrations.AlterModelTable(
            name='emailsentrecord',
            table='email_sent_records',
        ),
        migrations.AlterModelTable(
            name='googleintegration',
            table='google_integrations',
        ),
    ]
