# Generated by Django 4.2.23 on 2025-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_integration', '0003_alter_autoapplysession_options_and_more'),
    ]

    operations = [
        # Fix the refresh_token_encrypted field to properly allow NULL values
        migrations.AlterField(
            model_name='googleintegration',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
