# Generated by Django 4.2.23 on 2025-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_integration', '0005_auto_20250728_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleintegration',
            name='access_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='googleintegration',
            name='refresh_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
