# Generated by Django 5.2.4 on 2025-07-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatchscore',
            name='rank_score',
            field=models.IntegerField(blank=True, help_text='Rank among all jobs for this user', null=True),
        ),
    ]
