# Generated by Django 4.2.23 on 2025-07-25 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='api_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_application_limit',
            field=models.IntegerField(default=5, help_text='Maximum applications per day'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20),
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscription_plans',
        ),
        migrations.AlterModelTable(
            name='usersubscription',
            table='user_subscriptions',
        ),
        migrations.CreateModel(
            name='DailyApplicationUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('applications_count', models.IntegerField(default=0)),
                ('companies_applied', models.JSONField(default=list, help_text='List of company IDs applied to today')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_application_usage',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
