# Generated by Django 4.2.23 on 2025-07-26 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Category name (e.g., 'Full Stack Developer', 'Plumber', 'Cook')", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the category name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for automatic categorization')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_category',
            field=models.ForeignKey(blank=True, help_text='Automatically assigned job category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='jobs.jobcategory'),
        ),
    ]
