# Generated by Django 4.2.23 on 2025-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobcategory_jobposting_job_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_category', 'status'], name='job_posting_job_cat_e80656_idx'),
        ),
    ]
