# Generated by Django 4.2.23 on 2025-07-28 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_job_posting_job_cat_e80656_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_jobapplication_external_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAppliedJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('application_method', models.CharField(choices=[('email', 'Email to Company'), ('external_redirect', 'External Website'), ('api', 'API Integration')], default='email', max_length=20)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('skipped', 'Skipped'), ('bounced', 'Email Bounced')], default='pending', max_length=20)),
                ('company_email', models.EmailField(blank=True, help_text='Email address the application was sent to', max_length=254)),
                ('gmail_message_id', models.CharField(blank=True, help_text='Gmail API message ID', max_length=255)),
                ('cover_letter_sent', models.TextField(blank=True, help_text='Cover letter content that was sent')),
                ('resume_attached', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_applications', to='jobs.jobposting')),
                ('job_application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_applied_record', to='applications.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_applied_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_applied_jobs',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
